// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiSOSPet
{
    public partial class Ocorrencia
    {
        [Key]
        [Column("IDocorr")]
        public long Idocorr { get; set; }
        [Required]
        [Column("status")]
        [StringLength(50)]
        public string Status { get; set; }
        [Required]
        [Column("tipo")]
        [StringLength(50)]
        public string Tipo { get; set; }
        [Required]
        [Column("descricao")]
        [StringLength(500)]
        public string Descricao { get; set; }
        [Column("localizacao_lat")]
        public double LocalizacaoLat { get; set; }
        [Column("localizacao_long")]
        public double LocalizacaoLong { get; set; }
        [Column("data_ocorrencia", TypeName = "datetime")]
        public DateTime? DataOcorrencia { get; set; }
        [Column("IDanimal")]
        public long? Idanimal { get; set; }
        [Column("IDusuario")]
        public long? Idusuario { get; set; }

        [ForeignKey(nameof(Idanimal))]
        [InverseProperty(nameof(Animal.Ocorrencia))]
        public virtual Animal IdanimalNavigation { get; set; }
        [ForeignKey(nameof(Idusuario))]
        [InverseProperty(nameof(Usuario.Ocorrencia))]
        public virtual Usuario IdusuarioNavigation { get; set; }
    }
}