// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ApiSOSPet
{
    public partial class SospetContext : DbContext
    {
        public SospetContext()
        {
        }

        public SospetContext(DbContextOptions<SospetContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Animal> Animais { get; set; }
        public virtual DbSet<Ocorrencia> Ocorrencias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-HCMJ2FO;Initial Catalog=SOSPet;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Animal>(entity =>
            {
                entity.Property(e => e.Especie).IsUnicode(false);

                entity.Property(e => e.Foto).IsUnicode(false);

                entity.Property(e => e.Porte)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Raca).IsUnicode(false);
            });

            modelBuilder.Entity<Ocorrencia>(entity =>
            {
                entity.HasKey(e => e.Idocorr)
                    .HasName("PK__Ocorrenc__55437AF47EEAD4DD");

                entity.Property(e => e.Descricao).IsUnicode(false);

                entity.Property(e => e.Status).IsUnicode(false);

                entity.Property(e => e.Tipo).IsUnicode(false);

                entity.HasOne(d => d.IdanimalNavigation)
                    .WithMany(p => p.Ocorrencia)
                    .HasForeignKey(d => d.Idanimal)
                    .HasConstraintName("FK__Ocorrenci__IDani__4AB81AF0");

                entity.HasOne(d => d.IdusuarioNavigation)
                    .WithMany(p => p.Ocorrencia)
                    .HasForeignKey(d => d.Idusuario)
                    .HasConstraintName("FK__Ocorrenci__IDusu__49C3F6B7");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}