// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApiSOSPet
{
    public partial class Usuario
    {
        public Usuario()
        {
            Ocorrencia = new HashSet<Ocorrencia>();
        }

        [Key]
        [Column("id")]
        public long Id { get; set; }
        [Required]
        [Column("nome")]
        [StringLength(255)]
        public string Nome { get; set; }
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [Column("telefone")]
        [StringLength(20)]
        public string Telefone { get; set; }
        [Required]
        [Column("senha")]
        [StringLength(50)]
        public string Senha { get; set; }

        [InverseProperty("IdusuarioNavigation")]
        public virtual ICollection<Ocorrencia> Ocorrencia { get; set; }
    }
}